// import "./components/Map";
import "./Text";
import "./SimpleColumn";
import "./DoubleColumn";
import "./TripleColumn";
import "./Button";
// import "./components/Image";
import "./Navbar";
import "./Dropdown";
import "./Card";