// import "./Map";
import "./Text";
import "./SimpleColumn";
import "./DoubleColumn";
import "./TripleColumn";
import "./Button";
// import "./Image";
import "./Navbar";
import "./Dropdown";
import "./Card";