// import "./Map";
import "./Text";
import "./SimpleColumn";
import "./DoubleColumn";
import "./TripleColumn";
import "./Button";
// import "./Image";
import "./Navbar";
import "./Dropdown";
import "./CardProduct";
import "./CardProfile";
import "./CardFlip";
import "./Tooltip";
import "./Carousel";
import "./RadioButton";
import "./MegaMenu";
import "./Modal";